const enc=new TextEncoder();
const J=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
const now=()=>new Date().toISOString();
const uid=p=>`${p}_${crypto.randomUUID()}`;
const txt=(v,n=4000)=>String(v??"").trim().slice(0,n);
async function body(req){try{return await req.json()}catch{return {}}}
async function sign(secret,value){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=await crypto.subtle.sign("HMAC",key,enc.encode(value));return btoa(String.fromCharCode(...new Uint8Array(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function makeSession(env){const exp=String(Date.now()+8*60*60*1000);return `${exp}.${await sign(env.SESSION_SECRET,exp)}`}
async function authed(req,env){const c=req.headers.get("cookie")||"";const m=c.match(/(?:^|;\s*)alex_orienta_session=([^;]+)/);if(!m)return false;const [exp,sig]=m[1].split(".");if(!exp||!sig||Number(exp)<=Date.now())return false;return sig===await sign(env.SESSION_SECRET,exp)}
const risky=t=>["me quiero matar","quiero morir","no quiero vivir","hacerme daño","lastimarme","matarme","suicid","autoles"].some(x=>String(t||"").toLowerCase().includes(x));

async function api(req,env,url){const p=url.pathname;
 if(p==="/api/admin/login"&&req.method==="POST"){const b=await body(req);if(!env.ADMIN_PASSWORD||!env.SESSION_SECRET)return J({error:"Faltan Secrets ADMIN_PASSWORD y SESSION_SECRET."},500);if(txt(b.password,200)!==env.ADMIN_PASSWORD)return J({error:"Contraseña incorrecta"},401);return J({ok:true},200,{"set-cookie":`alex_orienta_session=${await makeSession(env)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}
 if(p==="/api/admin/logout"&&req.method==="POST")return J({ok:true},200,{"set-cookie":"alex_orienta_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"});
 if(p==="/api/admin/session"&&req.method==="GET")return J({authenticated:await authed(req,env)});
 if(p==="/api/appointments"&&req.method==="POST"){const b=await body(req),name=txt(b.client_name,120),date=txt(b.preferred_date,20),time=txt(b.preferred_time,20);if(!name||!date||!time)return J({error:"Nombre, fecha y horario son obligatorios."},400);const age=b.age===""||b.age==null?null:Number(b.age),minor=Number.isFinite(age)&&age<18?1:0;if(minor&&!txt(b.guardian_name,120))return J({error:"Para menores necesitamos el nombre del padre, madre o tutor."},400);const n=now();await env.DB.prepare(`INSERT INTO appointments(id,client_name,age,client_email,client_phone,is_minor,guardian_name,guardian_email,guardian_phone,service_type,reason_summary,preferred_date,preferred_time,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'requested',?,?)`).bind(uid("appt"),name,Number.isFinite(age)?age:null,txt(b.client_email,160),txt(b.client_phone,40),minor,txt(b.guardian_name,120),txt(b.guardian_email,160),txt(b.guardian_phone,40),txt(b.service_type,80)||"orientacion_vocacional",txt(b.reason_summary,1500),date,time,n,n).run();return J({ok:true})}
 if(p.startsWith("/api/admin/")&&!(await authed(req,env)))return J({error:"No autorizado"},401);
 if(p==="/api/admin/dashboard"&&req.method==="GET"){const [r,c,pe,ri]=await Promise.all([env.DB.prepare("SELECT COUNT(*) count FROM appointments WHERE status='requested'").first(),env.DB.prepare("SELECT COUNT(*) count FROM appointments WHERE status='confirmed'").first(),env.DB.prepare("SELECT COUNT(*) count FROM people WHERE status='active'").first(),env.DB.prepare("SELECT COUNT(*) count FROM ai_messages WHERE risk_flag=1").first()]);return J({requested:r?.count||0,confirmed:c?.count||0,active_people:pe?.count||0,risk_messages:ri?.count||0})}
 if(p==="/api/admin/appointments"&&req.method==="GET"){const {results}=await env.DB.prepare("SELECT * FROM appointments ORDER BY preferred_date,preferred_time").all();return J({appointments:results||[]})}
 if(p==="/api/admin/appointments/status"&&req.method==="POST"){const b=await body(req);if(!new Set(["requested","confirmed","completed","cancelled"]).has(b.status))return J({error:"Estado inválido"},400);await env.DB.prepare("UPDATE appointments SET status=?,updated_at=? WHERE id=?").bind(b.status,now(),txt(b.id,120)).run();return J({ok:true})}
 if(p==="/api/admin/people"&&req.method==="GET"){const {results}=await env.DB.prepare(`SELECT p.*,(SELECT COUNT(*) FROM private_notes n WHERE n.person_id=p.id) note_count,(SELECT COUNT(*) FROM ai_messages m WHERE m.person_id=p.id AND m.risk_flag=1) risk_count FROM people p ORDER BY p.updated_at DESC`).all();return J({people:results||[]})}
 if(p==="/api/admin/people"&&req.method==="POST"){const b=await body(req),name=txt(b.full_name,120);if(!name)return J({error:"Nombre obligatorio"},400);const age=b.age===""||b.age==null?null:Number(b.age),minor=Number.isFinite(age)&&age<18?1:0,pid=uid("person"),n=now();await env.DB.prepare(`INSERT INTO people(id,full_name,age,email,phone,is_minor,guardian_name,guardian_email,guardian_phone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'active',?,?)`).bind(pid,name,Number.isFinite(age)?age:null,txt(b.email,160),txt(b.phone,40),minor,txt(b.guardian_name,120),txt(b.guardian_email,160),txt(b.guardian_phone,40),n,n).run();await env.DB.prepare("INSERT INTO vocational_profiles(person_id,updated_at) VALUES(?,?)").bind(pid,n).run();return J({ok:true,person_id:pid})}
 if(p.startsWith("/api/admin/person/")&&req.method==="GET"){const pid=p.split("/").pop();const person=await env.DB.prepare("SELECT * FROM people WHERE id=?").bind(pid).first();if(!person)return J({error:"Persona no encontrada"},404);const {results:notes}=await env.DB.prepare("SELECT * FROM private_notes WHERE person_id=? ORDER BY created_at DESC").bind(pid).all();const vocational=await env.DB.prepare("SELECT * FROM vocational_profiles WHERE person_id=?").bind(pid).first();return J({person,notes:notes||[],vocational:vocational||null})}
 if(p==="/api/admin/note"&&req.method==="POST"){const b=await body(req),pid=txt(b.person_id,120),note=txt(b.note_text,8000);if(!pid||!note)return J({error:"Faltan datos"},400);const n=now();await env.DB.prepare("INSERT INTO private_notes(id,person_id,note_text,created_at,updated_at) VALUES(?,?,?,?,?)").bind(uid("note"),pid,note,n,n).run();await env.DB.prepare("UPDATE people SET updated_at=? WHERE id=?").bind(n,pid).run();return J({ok:true})}
 if(p==="/api/admin/vocational"&&req.method==="POST"){const b=await body(req),pid=txt(b.person_id,120);if(!pid)return J({error:"Selecciona una persona"},400);await env.DB.prepare(`INSERT INTO vocational_profiles(person_id,interests,strengths,values_text,favorite_subjects,work_style,careers_considered,open_questions,guidance_plan,ai_context,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(person_id) DO UPDATE SET interests=excluded.interests,strengths=excluded.strengths,values_text=excluded.values_text,favorite_subjects=excluded.favorite_subjects,work_style=excluded.work_style,careers_considered=excluded.careers_considered,open_questions=excluded.open_questions,guidance_plan=excluded.guidance_plan,ai_context=excluded.ai_context,updated_at=excluded.updated_at`).bind(pid,txt(b.interests),txt(b.strengths),txt(b.values_text),txt(b.favorite_subjects),txt(b.work_style),txt(b.careers_considered),txt(b.open_questions),txt(b.guidance_plan,5000),txt(b.ai_context,5000),now()).run();return J({ok:true})}
 if(p==="/api/admin/ai-reflection"&&req.method==="POST"){const b=await body(req),pid=txt(b.person_id,120),message=txt(b.message,4000);if(!pid||!message)return J({error:"Selecciona una persona y escribe un mensaje."},400);if(risky(message)){const reply="Lo que escribes puede indicar que necesitas apoyo humano inmediato. Este espacio no es adecuado para manejar una crisis. Si existe riesgo de hacerte daño o estás en peligro, busca de inmediato a un adulto de confianza, a Alex u otro profesional, o contacta los servicios de emergencia de tu localidad.";const n=now();await env.DB.prepare("INSERT INTO ai_messages(id,person_id,role,content,risk_flag,created_at) VALUES(?,?,'user',?,1,?)").bind(uid("msg"),pid,message,n).run();await env.DB.prepare("INSERT INTO ai_messages(id,person_id,role,content,risk_flag,created_at) VALUES(?,?,'assistant',?,1,?)").bind(uid("msg"),pid,reply,n).run();return J({ok:true,risk_flag:true,reply})}
 const person=await env.DB.prepare("SELECT * FROM people WHERE id=?").bind(pid).first();const v=await env.DB.prepare("SELECT * FROM vocational_profiles WHERE person_id=?").bind(pid).first();const system=`Eres Espacio de Reflexión, herramienta de orientación vocacional y desarrollo personal supervisada por Alex. No eres terapeuta. No diagnostiques, no recomiendes medicamentos, no sustituyas atención profesional y no decidas la carrera por la persona. Ayuda con preguntas, reflexión estructurada y comparación de opciones. Responde breve y natural en español.\nNombre: ${person?.full_name||"Persona"}\nEdad: ${person?.age??"No indicada"}\nIntereses: ${v?.interests||"No registrados"}\nFortalezas: ${v?.strengths||"No registradas"}\nValores: ${v?.values_text||"No registrados"}\nCarreras consideradas: ${v?.careers_considered||"No registradas"}\nPlan de orientación: ${v?.guidance_plan||"Sin plan"}\nContexto permitido por Alex: ${v?.ai_context||"Ninguno"}\nLas notas privadas de Alex NO forman parte del contexto.`;const r=await env.AI.run("@cf/zai-org/glm-4.7-flash",{messages:[{role:"system",content:system},{role:"user",content:message}]});const reply=r?.response||r?.result?.response||r?.choices?.[0]?.message?.content||"No pude responder en este momento.";const n=now();await env.DB.prepare("INSERT INTO ai_messages(id,person_id,role,content,risk_flag,created_at) VALUES(?,?,'user',?,0,?)").bind(uid("msg"),pid,message,n).run();await env.DB.prepare("INSERT INTO ai_messages(id,person_id,role,content,risk_flag,created_at) VALUES(?,?,'assistant',?,0,?)").bind(uid("msg"),pid,txt(reply,6000),n).run();return J({ok:true,risk_flag:false,reply})}
 return J({error:"Ruta no encontrada"},404)
}
export default{async fetch(req,env){const url=new URL(req.url);return url.pathname.startsWith("/api/")?api(req,env,url):env.ASSETS.fetch(req)}};
